Add a widget
smartdevicelink/sdl_example_weather_app_ios pull request #25
Opened 2022-01-04 16:35 UTC by joeljfischer

* Adds a basic widget
* Adds group boxes to main UI

2022-01-31 14:17 UTC, FrankElias77 requested changes

2022-01-31 14:17 UTC, FrankElias77 commented on MobileWeather/APIKey.swift
> +    static let apiKey = "d6f1f15f251280a3908a846151e9e61c"
I think you forgot to remove your apiKey

2022-01-31 14:17 UTC, FrankElias77 commented on MobileWeather/DailyConditionsView.swift
> +
```suggestion

```

2022-01-31 14:17 UTC, FrankElias77 commented on MobileWeather/DailyConditionsView.swift
> +
```suggestion

```

2022-01-31 14:17 UTC, FrankElias77 commented on SDL Weather Widget/Info.plist
> +	<key>NSWidgetWantsLocation</key>
```suggestion
        <key>NSLocationWhenInUseUsageDescription</key>
        <string>SDL Weather uses your location to find the weather where you are</string>
	<key>NSWidgetWantsLocation</key>
```

2022-01-31 15:26 UTC, joeljfischer commented on MobileWeather/APIKey.swift
> +    static let apiKey = "d6f1f15f251280a3908a846151e9e61c"
Fixed and deactivated

2022-02-01 19:17 UTC, FrankElias77 approved these changes

2022-02-02 14:17 UTC, merged